---
alias: "Bedroom Floor Lamp"
trigger:
  - platform: device
    device_id: b975e5976ffa4bb5a782c12486960b1b
    domain: zha
    type: remote_button_double_press
    subtype: remote_button_double_press
  - platform: device
    device_id: 81a1780b08d64feebb3cad72cfccdea0
    domain: zha
    type: remote_button_double_press
    subtype: remote_button_double_press
condition:
action:
  - service: light.toggle
    entity_id: light.bedroom_floor_lamp
