---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files

  - repo: https://github.com/prettier/prettier
    rev: 2.0.4
    hooks:
      - id: prettier

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.22.1
    hooks:
      - id: yamllint
