---
- platform: mjpeg
  name: "Backyard Camera"
  still_image_url: "http://192.168.0.19:8080/{{ shinobi_api_key }}/jpeg/Tlyusm5HOn/camera01/s.jpg"
  mjpeg_url: "http://192.168.0.19:8080/{{ shinobi_api_key }}/mjpeg/Tlyusm5HOn/camera01"

- platform: mjpeg
  name: "Master Bedroom Camera"
  still_image_url: "http://192.168.0.19:8080/{{ shinobi_api_key }}/jpeg/Tlyusm5HOn/camera02/s.jpg"
  mjpeg_url: "http://192.168.0.19:8080/{{ shinobi_api_key }}/mjpeg/Tlyusm5HOn/camera02"

- platform: mjpeg
  name: "Front Door Camera"
  still_image_url: "http://192.168.0.19:8080/{{ shinobi_api_key }}/jpeg/Tlyusm5HOn/camera03/s.jpg"
  mjpeg_url: "http://192.168.0.19:8080/{{ shinobi_api_key }}/mjpeg/Tlyusm5HOn/camera03"
