---
alias: 'Motion Turn Off Kitchen Lights'
trigger:
  platform: 'state'
  entity_id: 'binary_sensor.kitchen_motion_detector'
  to: 'off'
  for:
    minutes: 10
action:
  service: 'light.turn_off'
  entity_id: 'light.kitchen_lights'
