---
alias: "Motion Turn On Kitchen Lights"
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_motion_detector
  to: 'on'
action:
  service: light.turn_on
  entity_id: light.kitchen_lights
  data_template:
    brightness: "{% if now().hour > 21 or now().hour < 6 %}64{% else %}255{% endif %}"
