---
alias: "Disarm When Home"
trigger:
  platform: state
  entity_id: group.all_people
  from: 'not_home'
  to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm_control_panel
      state: armed_away
action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm_control_panel
