---
alias: "Disable Kitchen Motion Lights"

trigger:

condition:

action:
  - service: automation.turn_off
    entity_id: automation.motion_turn_on_kitchen_lights
  - service: automation.turn_off
    entity_id: automation.motion_turn_off_kitchen_lights
