---
alias: "Garage Door Still Open"

trigger:
  - platform: time
    at: "21:00:00"

  - platform: state
    entity_id: person.autumn, person.kevin
    from: "home"
    to: "not_home"

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.garage_door
      state: "on"

action:
  - service: notify.notify
    data:
      title: "Garage Door"
      message: "The garage door is still open."
