---
alias: "House On"

trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion_detector
    to: "on"

condition:

action:
  - service: scene.turn_on
    entity_id:
      - scene.kitchen_bright
      - scene.living_room_bright
  - service: automation.turn_off
    entity_id: automation.house_on
