---
alias: "Kevins Night Stand Button"
trigger:
  platform: device
  device_id: 81a1780b08d64feebb3cad72cfccdea0
  domain: zha
  type: remote_button_short_press
  subtype: remote_button_short_press
condition:
action:
  - service: light.toggle
    entity_id: light.kevins_night_stand_light
