---
alias: "Late Arrival"

trigger:
  platform: state
  entity_id: group.all_people
  from: "not_home"
  to: "home"

condition:
  condition: and
  conditions:
    - condition: time
      after: "21:00:00"
      before: "06:00:00"

action:
  - delay: "0:15"
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.home_alarm_control_panel
