---
alias: "Movie Time"
trigger:
condition:
action:
  - service: scene.create
    data:
      scene_id: scene_restore
      snapshot_entities:
        - light.living_room_lights
        - light.kitchen_lights
  - service: scene.turn_on
    entity_id: scene.movie_time
