---
alias: "When we leave"
trigger:
  platform: state
  entity_id: group.all_people
  from: "home"
  to: "not_home"
condition:
action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm_control_panel
  - service: "scene.turn_on"
    entity_id:
      - "scene.living_room_dim"
  - service: "light.turn_off"
    entity_id:
      - "light.kitchen_lights"
