---
alias: "When we get home"
trigger:
  platform: state
  entity_id: group.all_people
  from: "not_home"
  to: "home"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: alarm_control_panel.home_alarm_control_panel
      state: armed_away
    - condition: time
      after: "06:00:00"
      before: "21:00:00"
action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm_control_panel
  - service: scene.turn_on
    entity_id:
      - scene.kitchen_bright
      - scene.living_room_bright
