---
alias: "Will Bedtime"

trigger:
  - platform: time
    at: "18:30:00"

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.all_people
      state: "home"

action:
  - service: scene.turn_on
    entity_id:
      - scene.kitchen_dim
      - scene.living_room_dim
