---
weather:
  platform: openweathermap
  api_key: !secret openweathermap_api_key

sensor:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    monitored_conditions:
      - temperature
