name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        path: 'config'

      - name: Move fake secrets into config
        run: mv ./config/.stubs/secrets.yaml ./config/secrets.yaml

      - name: Check config
        run: python -m homeassistant --script check_config --config /config
        services:
          image: homeassistant/home-assistant:stable
          volumes:
            - $GITHUB_WORKSPACE/config:/config
          options: --entrypoint ""
