name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: homeassistant/home-assistant:stable
      volumes:
        - /:/config
    steps:
      - name: Move fake secrets into config
        run: mv /config/.stubs/secrets.yaml /config/secrets.yaml

      - name: Check config
        run: python -m homeassistant --script check_config --config /config
