name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: homeassistant/home-assistant:stable
    steps:
      - uses: actions/checkout@v2

      - name: Copy config into place
        run: cp -R $GITHUB_WORKSPACE/. /config/

      - name: Move fake secrets into config
        run: mv /config/.stubs/secrets.yaml /config/secrets.yaml

      - name: Check config
        run: python -m homeassistant --script check_config --config /config --files
